
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Provider from "./_components/Provider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body >
        <Toaster toastOptions={{ duration: 3000}} />
      <div className="flex flex-col relative min-h-screen">
        <Provider>
          {children}
        </Provider>
      </div>
      <footer className="fixed bottom-0 w-full text-center text-sm text-gray-500 py-3 bg-white border-t">
        Developed by Khandyana Manindra
      </footer>
      </body>
      
    </html>
  );
}
